name: publish Mehedi.CleanArchitecture Template to nuget
on:
  push:
    branches:
      - master # Your default release branch
    paths:
      - 'Mehedi.CleanArchitecture.Template.nuspec'
      - 'src/Presentation/Mehedi.CleanArchitecture.Api/**'
jobs:
  publish:
    name: Publish on nuget
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'

      # Read the existing version and increment the last digit
      - name: Bump version
        id: version
        shell: pwsh
        run: |
          $nuspecFile = "Mehedi.CleanArchitecture.Template.nuspec"
          
          # Read the existing version from .nuspec
          $content = Get-Content $nuspecFile -Raw
          if ($content -match '<version>(\d+)\.(\d+)\.(\d+)</version>') {
            $major = $matches[1]
            $minor = $matches[2]
            $patch = [int]$matches[3] + 1  # Increment last version number

            $newVersion = "$major.$minor.$patch"
            echo "NEW_VERSION=$newVersion" >> $env:GITHUB_ENV
            Write-Output "New Version: $newVersion"

            # Update the .nuspec file with the new version
            $updatedContent = $content -replace '<version>(\d+)\.(\d+)\.(\d+)</version>', "<version>$newVersion</version>"
            $updatedContent | Set-Content $nuspecFile
          } else {
            Write-Error "Failed to read version from $nuspecFile"
            exit 1
          }

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git config --global credential.helper store
          
          git add .
          git commit -m "Update nuget package version to ${{ steps.bump.outputs.newVersion }}"
          git push 
          
      - name: Package the template
        run: nuget pack Mehedi.CleanArchitecture.Template.nuspec -NoDefaultExcludes
        
      - name: Publish to nuget.org
        run: nuget push Mehedi.CleanArchitecture.Template.*.nupkg -src https://api.nuget.org/v3/index.json ${{secrets.NUGET_API_KEY}}
